#!/usr/bin/env bash

echo "Starting build process..."
echo Backing up old www to .cache/showroom/www

if [ ! -d ".cache/showroom" ]; then
  mkdir -p .cache/showroom
fi

cp -r ./www .cache/showroom/www

echo "Removing old site..."

rm -rf ./www/*

echo "Building new site..."

# Setup Container Runtime
current_dir="$(dirname "$(realpath "$0")")"
source $current_dir/detect-container-runtime

volume_mount_flag=""
platform_flag=""
os_name="$(uname -s)" # Detect the operating system, Linux needs `:z` macos does not

# Set the volume mount flag to ":z" if the OS is Linux
if [ "$os_name" = "Linux" ]; then
  volume_mount_flag=":z"
  platform_flag="--platform linux/amd64"
fi

${CONTAINER_RUNTIME} \
  run --rm --name showroom-builder \
  ${platform_flag} \
  -v "./:/antora${volume_mount_flag}" \
  docker.io/antora/antora default-site.yml

echo "Build process complete. Check the ./www folder for the generated site."
echo "To view the site locally, run the following command: utilities/lab-serve"
echo "If already running then browse to http://localhost:8443/index.html"
