#!/usr/bin/env bash

echo "Starting serve process..."
# TODO: Add case statement to allow stopping, starting, and restarting

# Setup Container Runtime
current_dir="$(dirname "$(realpath "$0")")"
source $current_dir/detect-container-runtime

# TODO: Move to RHEL image
${CONTAINER_RUNTIME} run -d --rm --name showroom-httpd -p 8443:80 -v "./www:/usr/local/apache2/htdocs/" docker.io/httpd:2.4
echo "Serving lab content on http://localhost:8443/index.html"
