#!/usr/bin/env bash

echo "Stopping serve process..."
# Setup Container Runtime
current_dir="$(dirname "$(realpath "$0")")"
source $current_dir/detect-container-runtime

${CONTAINER_RUNTIME} kill showroom-httpd
echo "Stopped serve process."
